import { execSync } from 'child_process'

var handler = async (m, { conn, text, isROwner }) => {
if (!isROwner) return
await m.react('üïí')
try {
const stdout = execSync('git pull' + (m.fromMe && text ? ' ' + text : ''));
let messager = stdout.toString()
if (messager.includes('üéÄ The update is now loaded.')) messager = 'üíó The data is now updated to the latest version..'
if (messager.includes('üå∑ Updating.')) messager = 'üéÄ Processing, please wait a moment while I update..\n\n' + stdout.toString()
await m.react('‚úîÔ∏è')
conn.reply(m.chat, messager, m)
} catch { 
try {
const status = execSync('git status --porcelain')
if (status.length > 0) {
const conflictedFiles = status.toString().split('\n').filter(line => line.trim() !== '').map(line => {
if (line.includes('.npm/') || line.includes('.cache/') || line.includes('tmp/') || line.includes('database.json') || line.includes('sessions/Principal/') || line.includes('npm-debug.log')) {
return null
}
return '*‚Üí ' + line.slice(3) + '*'}).filter(Boolean)
if (conflictedFiles.length > 0) {
const errorMessage = `\`‚ö†Ô∏é The update could not be performed:\`\n\n> *Local changes have been found in the bot files that conflict with new repository updates..*\n\n${conflictedFiles.join('\n')}.`
await conn.reply(m.chat, errorMessage, m)
await m.react('‚úñÔ∏è')
}}} catch (error) {
console.error(error)
let errorMessage2 = '‚ö†Ô∏é An unexpected error occurred.'
if (error.message) {
errorMessage2 += '\n‚ö†Ô∏é Error message: ' + error.message
}
await conn.reply(m.chat, errorMessage2, m)
}}}

handler.help = ['update']
handler.tags = ['owner']
handler.command = ['update', 'fix', 'actualizar']

export default handler
